//mockaroo for test data import

const student = [{
    "id": 1,
    "first_name": "Lorenzo",
    "last_name": "Asling"
  }, {
    "id": 2,
    "first_name": "Hans",
    "last_name": "Luparti"
  }, {
    "id": 3,
    "first_name": "Roderich",
    "last_name": "Sleeny"
  }, {
    "id": 4,
    "first_name": "Farris",
    "last_name": "Arnot"
  }, {
    "id": 5,
    "first_name": "Bunny",
    "last_name": "Vasyushkhin"
  }, {
    "id": 6,
    "first_name": "Rob",
    "last_name": "Acland"
  }, {
    "id": 7,
    "first_name": "Clemence",
    "last_name": "Thebeaud"
  }, {
    "id": 8,
    "first_name": "Peirce",
    "last_name": "Arcase"
  }, {
    "id": 9,
    "first_name": "Oriana",
    "last_name": "Stoad"
  }, {
    "id": 10,
    "first_name": "Blair",
    "last_name": "Stiggles"
  }, {
    "id": 11,
    "first_name": "Jillian",
    "last_name": "Letten"
  }, {
    "id": 12,
    "first_name": "Marylou",
    "last_name": "Penwell"
  }, {
    "id": 13,
    "first_name": "Wenonah",
    "last_name": "Jessopp"
  }, {
    "id": 14,
    "first_name": "Serene",
    "last_name": "Blowes"
  }, {
    "id": 15,
    "first_name": "Mauricio",
    "last_name": "Mawer"
  }, {
    "id": 16,
    "first_name": "Vinny",
    "last_name": "Tallyn"
  }, {
    "id": 17,
    "first_name": "Odette",
    "last_name": "Greaves"
  }, {
    "id": 18,
    "first_name": "Fionnula",
    "last_name": "Durtnal"
  }, {
    "id": 19,
    "first_name": "Breanne",
    "last_name": "Rewan"
  }, {
    "id": 20,
    "first_name": "Mirna",
    "last_name": "Cronkshaw"
  }, {
    "id": 21,
    "first_name": "Dominick",
    "last_name": "Furzey"
  }, {
    "id": 22,
    "first_name": "Bonnibelle",
    "last_name": "Pinor"
  }, {
    "id": 23,
    "first_name": "Clark",
    "last_name": "Taree"
  }, {
    "id": 24,
    "first_name": "Hailey",
    "last_name": "Eldritt"
  }, {
    "id": 25,
    "first_name": "Augusto",
    "last_name": "Kimble"
  }, {
    "id": 26,
    "first_name": "Simonne",
    "last_name": "Demaid"
  }, {
    "id": 27,
    "first_name": "Cletus",
    "last_name": "Le Estut"
  }, {
    "id": 28,
    "first_name": "Carce",
    "last_name": "Skune"
  }, {
    "id": 29,
    "first_name": "Paco",
    "last_name": "Dudney"
  }, {
    "id": 30,
    "first_name": "Henryetta",
    "last_name": "Riccardelli"
  }, {
    "id": 31,
    "first_name": "Zaneta",
    "last_name": "Belasco"
  }, {
    "id": 32,
    "first_name": "Jaime",
    "last_name": "Gillimgham"
  }, {
    "id": 33,
    "first_name": "Nollie",
    "last_name": "Wilcock"
  }, {
    "id": 34,
    "first_name": "Mile",
    "last_name": "Fennelow"
  }, {
    "id": 35,
    "first_name": "Bernie",
    "last_name": "Dawney"
  }, {
    "id": 36,
    "first_name": "Nickola",
    "last_name": "Mayworth"
  }, {
    "id": 37,
    "first_name": "Isak",
    "last_name": "James"
  }, {
    "id": 38,
    "first_name": "Delano",
    "last_name": "Hurn"
  }, {
    "id": 39,
    "first_name": "Rickert",
    "last_name": "Tarbin"
  }, {
    "id": 40,
    "first_name": "Kira",
    "last_name": "Nanninini"
  }, {
    "id": 41,
    "first_name": "Malchy",
    "last_name": "Devonshire"
  }, {
    "id": 42,
    "first_name": "Bobine",
    "last_name": "Raimbauld"
  }, {
    "id": 43,
    "first_name": "Tuesday",
    "last_name": "Burry"
  }, {
    "id": 44,
    "first_name": "Corella",
    "last_name": "Poole"
  }, {
    "id": 45,
    "first_name": "Waldo",
    "last_name": "Lomath"
  }, {
    "id": 46,
    "first_name": "Althea",
    "last_name": "Barr"
  }, {
    "id": 47,
    "first_name": "Lilia",
    "last_name": "Le Friec"
  }, {
    "id": 48,
    "first_name": "Lula",
    "last_name": "O'Fihillie"
  }, {
    "id": 49,
    "first_name": "Opaline",
    "last_name": "Domenico"
  }, {
    "id": 50,
    "first_name": "Derril",
    "last_name": "Rosingdall"
  }, {
    "id": 51,
    "first_name": "Nels",
    "last_name": "Oleszczak"
  }, {
    "id": 52,
    "first_name": "Beaufort",
    "last_name": "Duinbleton"
  }, {
    "id": 53,
    "first_name": "Hynda",
    "last_name": "Belchamber"
  }, {
    "id": 54,
    "first_name": "Maggy",
    "last_name": "Haskett"
  }, {
    "id": 55,
    "first_name": "Flynn",
    "last_name": "Meysham"
  }, {
    "id": 56,
    "first_name": "Tammara",
    "last_name": "Phelan"
  }, {
    "id": 57,
    "first_name": "Stanly",
    "last_name": "Squibbs"
  }, {
    "id": 58,
    "first_name": "Duncan",
    "last_name": "Raccio"
  }, {
    "id": 59,
    "first_name": "Emmalyn",
    "last_name": "Lowrie"
  }, {
    "id": 60,
    "first_name": "Butch",
    "last_name": "Angier"
  }, {
    "id": 61,
    "first_name": "Micaela",
    "last_name": "Pexton"
  }, {
    "id": 62,
    "first_name": "Cynthie",
    "last_name": "Geistbeck"
  }, {
    "id": 63,
    "first_name": "Diana",
    "last_name": "Ostrich"
  }, {
    "id": 64,
    "first_name": "Trevor",
    "last_name": "Geraldi"
  }, {
    "id": 65,
    "first_name": "Donnajean",
    "last_name": "Sultana"
  }, {
    "id": 66,
    "first_name": "Raphael",
    "last_name": "Bugge"
  }, {
    "id": 67,
    "first_name": "Ethelbert",
    "last_name": "Gilbert"
  }, {
    "id": 68,
    "first_name": "Tristan",
    "last_name": "von Nassau"
  }, {
    "id": 69,
    "first_name": "Ailina",
    "last_name": "Goose"
  }, {
    "id": 70,
    "first_name": "Jacinta",
    "last_name": "Underhill"
  }, {
    "id": 71,
    "first_name": "Rice",
    "last_name": "Menure"
  }, {
    "id": 72,
    "first_name": "Riordan",
    "last_name": "Sine"
  }, {
    "id": 73,
    "first_name": "Kenneth",
    "last_name": "Remmer"
  }, {
    "id": 74,
    "first_name": "Elita",
    "last_name": "Demoge"
  }, {
    "id": 75,
    "first_name": "Jodie",
    "last_name": "Stammler"
  }, {
    "id": 76,
    "first_name": "Rowen",
    "last_name": "Gotthard.sf"
  }, {
    "id": 77,
    "first_name": "Alix",
    "last_name": "Aland"
  }, {
    "id": 78,
    "first_name": "Karil",
    "last_name": "Lintill"
  }, {
    "id": 79,
    "first_name": "Felike",
    "last_name": "Dwire"
  }, {
    "id": 80,
    "first_name": "Misha",
    "last_name": "Whitley"
  }, {
    "id": 81,
    "first_name": "Francoise",
    "last_name": "Billitteri"
  }, {
    "id": 82,
    "first_name": "Halsey",
    "last_name": "Benda"
  }, {
    "id": 83,
    "first_name": "Guntar",
    "last_name": "Strelitzer"
  }, {
    "id": 84,
    "first_name": "Ardelis",
    "last_name": "Guidera"
  }, {
    "id": 85,
    "first_name": "Tandi",
    "last_name": "Duns"
  }, {
    "id": 86,
    "first_name": "Eyde",
    "last_name": "Fri"
  }, {
    "id": 87,
    "first_name": "Homer",
    "last_name": "Wickstead"
  }, {
    "id": 88,
    "first_name": "Betteanne",
    "last_name": "Corness"
  }, {
    "id": 89,
    "first_name": "Madlen",
    "last_name": "Wannan"
  }, {
    "id": 90,
    "first_name": "Kimberli",
    "last_name": "Critten"
  }, {
    "id": 91,
    "first_name": "Collette",
    "last_name": "Collingham"
  }, {
    "id": 92,
    "first_name": "Cherlyn",
    "last_name": "Steele"
  }, {
    "id": 93,
    "first_name": "Burk",
    "last_name": "Beckworth"
  }, {
    "id": 94,
    "first_name": "Cammie",
    "last_name": "Legate"
  }, {
    "id": 95,
    "first_name": "Stefa",
    "last_name": "Romeuf"
  }, {
    "id": 96,
    "first_name": "Lilli",
    "last_name": "Antoni"
  }, {
    "id": 97,
    "first_name": "Leupold",
    "last_name": "DelaField"
  }, {
    "id": 98,
    "first_name": "Ricoriki",
    "last_name": "MacMenamin"
  }, {
    "id": 99,
    "first_name": "Keelia",
    "last_name": "Victor"
  }, {
    "id": 100,
    "first_name": "Guilbert",
    "last_name": "Dicky"
  }]
  
      
module.exports=student
